# Generated by Django 5.1.6 on 2025-03-18 22:47

import django.core.validators
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Preferiblemente PNG con fondo transparente (Recomendado 400x150 px)', keep_meta=True, null=True, quality=90, scale=None, size=[400, 200], upload_to='company/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
