# Generated by Django 5.1.6 on 2025-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={'ordering': ('-fecha_creacion',), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuarios_personalizados', related_query_name='usuario_personalizado', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('clientes', 'Gestor de Clientes'), ('contabilidad', 'Contabilidad'), ('reservas', 'Gestor de Reservas')], default='admin', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuarios_personalizados', related_query_name='usuario_personalizado', to='auth.permission', verbose_name='Permisos de usuario'),
        ),
    ]
