# Generated by Django 5.1.6 on 2025-03-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP de acceso'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Número de intentos fallidos de inicio de sesión', verbose_name='Intentos fallidos'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forzar cambio de contraseña en próximo inicio de sesión', verbose_name='Debe cambiar contraseña'),
        ),
    ]
