# Generated by Django 5.1.6 on 2025-03-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuariopersonalizado_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora'),
        ),
    ]
