# Generated by Django 5.1.6 on 2025-03-11 19:26

import crm.models
import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula_pasaporte', models.CharField(help_text='Números para cédula dominicana o número de pasaporte internacional', max_length=20, unique=True, verbose_name='Cédula/Pasaporte')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', django_countries.fields.CountryField(default='DO', max_length=2, verbose_name='Nacionalidad')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=100, verbose_name='Lugar de Trabajo')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('email', models.CharField(help_text='Ejemplo: nombre@dominio.com o N/A', max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('direccion_fisica', models.TextField(verbose_name='Dirección Física')),
                ('telefono', models.CharField(help_text='Formato internacional: +18091234567 o "N/A" si no aplica', max_length=20, verbose_name='Teléfono')),
                ('movil', models.CharField(help_text='Formato internacional: +18091234567 o "N/A" si no aplica', max_length=20, verbose_name='Móvil')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('potencial', 'Potencial')], default='activo', max_length=20, verbose_name='Estado del Lead')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_edicion', models.DateTimeField(auto_now=True, verbose_name='Última Edición')),
                ('documento', models.FileField(blank=True, null=True, upload_to='clientes/documentos/', verbose_name='Documento Adjunto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('contrato', 'Contrato'), ('identificacion', 'Identificación'), ('otros', 'Otros')], default='general', max_length=20, verbose_name='Tipo de documento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('archivo', models.FileField(upload_to=crm.models.documento_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Documento de cliente',
                'verbose_name_plural': 'Documentos de clientes',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('contrato', 'Contrato'), ('rnc', 'RNC'), ('otros', 'Otros')], default='general', max_length=20, verbose_name='Tipo de documento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('archivo', models.FileField(upload_to=crm.models.documento_empresa_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Documento de empresa',
                'verbose_name_plural': 'Documentos de empresas',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('rnc', models.CharField(help_text='Registro Nacional de Contribuyente', max_length=20, unique=True, verbose_name='RNC')),
                ('direccion_fisica', models.TextField(verbose_name='Dirección Física')),
                ('direccion_electronica', models.EmailField(max_length=254, unique=True, verbose_name='Dirección Electrónica')),
                ('telefono', models.CharField(help_text='Formato internacional: +18091234567', max_length=20, verbose_name='Teléfono Principal')),
                ('telefono2', models.CharField(blank=True, help_text='Formato internacional: +18091234567 (Opcional)', max_length=20, verbose_name='Teléfono Secundario')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('representante', models.CharField(max_length=200, verbose_name='Representante Legal')),
                ('cargo_representante', models.CharField(max_length=100, verbose_name='Cargo del Representante')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('potencial', 'Potencial')], default='activo', max_length=20, verbose_name='Estado')),
                ('documento', models.FileField(blank=True, null=True, upload_to='empresas/documentos/', verbose_name='Documento Adjunto')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='NotaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota de Cliente',
                'verbose_name_plural': 'Notas de Clientes',
                'ordering': ['-fecha_creacion'],
                'get_latest_by': 'fecha_creacion',
            },
        ),
        migrations.CreateModel(
            name='NotaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota de Empresa',
                'verbose_name_plural': 'Notas de Empresas',
                'ordering': ['-fecha_creacion'],
                'get_latest_by': 'fecha_creacion',
            },
        ),
    ]
