# Generated by Django 5.1.6 on 2025-02-12 17:37

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('cedula_pasaporte', models.CharField(max_length=20, unique=True, verbose_name='Cédula/Pasaporte')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2, verbose_name='Nacionalidad')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=100, verbose_name='Lugar de Trabajo')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('direccion_fisica', models.TextField(verbose_name='Dirección Física')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('movil', models.CharField(max_length=20, verbose_name='Móvil')),
                ('condicion_compra', models.CharField(choices=[('contado', 'Al Contado'), ('credito', 'Crédito'), ('financiado', 'Financiado')], default='contado', max_length=20, verbose_name='Condición de Compra')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('en_proceso', 'En Proceso'), ('convertido', 'Convertido')], default='nuevo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='clientes/documentos/', verbose_name='Documento Adjunto')),
            ],
        ),
    ]
