# Generated by Django 5.1.6 on 2025-02-18 22:17

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula_pasaporte', models.CharField(help_text='Números para cédula dominicana o número de pasaporte internacional', max_length=20, unique=True, verbose_name='Cédula/Pasaporte')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', django_countries.fields.CountryField(default='DO', max_length=2, verbose_name='Nacionalidad')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=100, verbose_name='Lugar de Trabajo')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('direccion_fisica', models.TextField(verbose_name='Dirección Física')),
                ('telefono', models.CharField(help_text='Formato internacional: +18091234567 o "N/A" si no aplica', max_length=20, verbose_name='Teléfono')),
                ('movil', models.CharField(help_text='Formato internacional: +18091234567 o "N/A" si no aplica', max_length=20, verbose_name='Móvil')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('potencial', 'Potencial')], default='nuevo', max_length=20, verbose_name='Estado del Lead')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('documento', models.FileField(blank=True, null=True, upload_to='clientes/documentos/', verbose_name='Documento Adjunto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['cedula_pasaporte'], name='crm_cliente_cedula__286563_idx'), models.Index(fields=['email'], name='crm_cliente_email_3bea01_idx')],
            },
        ),
    ]
