# Generated by Django 5.1.6 on 2025-02-22 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentocliente',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento de cliente', 'verbose_name_plural': 'Documentos de clientes'},
        ),
        migrations.AlterModelOptions(
            name='notacliente',
            options={'get_latest_by': 'fecha_creacion', 'ordering': ['-fecha_creacion'], 'verbose_name': 'Nota de Cliente', 'verbose_name_plural': 'Notas de Clientes'},
        ),
        migrations.AddIndex(
            model_name='documentocliente',
            index=models.Index(fields=['cliente', 'tipo'], name='crm_documen_cliente_e193c3_idx'),
        ),
    ]
