# Generated by Django 5.1.6 on 2025-02-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('potencial', 'Potencial')], default='activo', max_length=20, verbose_name='Estado del Lead'),
        ),
    ]
