# Generated by Django 5.1.6 on 2025-02-24 23:44

import crm.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('rnc', models.CharField(help_text='Registro Nacional de Contribuyente', max_length=20, unique=True, verbose_name='RNC')),
                ('direccion_fisica', models.TextField(verbose_name='Dirección Física')),
                ('direccion_electronica', models.EmailField(max_length=254, unique=True, verbose_name='Dirección Electrónica')),
                ('telefono', models.CharField(help_text='Formato internacional: +18091234567', max_length=20, verbose_name='Teléfono Principal')),
                ('telefono2', models.CharField(blank=True, help_text='Formato internacional: +18091234567 (Opcional)', max_length=20, verbose_name='Teléfono Secundario')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('representante', models.CharField(max_length=200, verbose_name='Representante Legal')),
                ('cargo_representante', models.CharField(max_length=100, verbose_name='Cargo del Representante')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('potencial', 'Potencial')], default='activo', max_length=20, verbose_name='Estado')),
                ('documento', models.FileField(blank=True, null=True, upload_to='empresas/documentos/', verbose_name='Documento Adjunto')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['rnc'], name='crm_empresa_rnc_07998e_idx'), models.Index(fields=['direccion_electronica'], name='crm_empresa_direcci_26446d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_empresa', to='crm.empresa')),
            ],
            options={
                'verbose_name': 'Nota de Empresa',
                'verbose_name_plural': 'Notas de Empresas',
                'ordering': ['-fecha_creacion'],
                'get_latest_by': 'fecha_creacion',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('contrato', 'Contrato'), ('rnc', 'RNC'), ('otros', 'Otros')], default='general', max_length=20, verbose_name='Tipo de documento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('archivo', models.FileField(upload_to=crm.models.documento_empresa_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Archivo')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_empresa', to='crm.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Documento de empresa',
                'verbose_name_plural': 'Documentos de empresas',
                'ordering': ['-fecha_subida'],
                'indexes': [models.Index(fields=['empresa', 'tipo'], name='crm_documen_empresa_deda89_idx')],
            },
        ),
    ]
