# Generated by Django 5.1.6 on 2025-02-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_empresa_notaempresa_documentoempresa'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nombre_comercial'], name='crm_empresa_nombre__3917ed_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['estado', 'fecha_registro'], name='crm_empresa_estado_acc481_idx'),
        ),
    ]
