# Generated by Django 5.1.6 on 2025-02-13 01:15

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidad',
            field=django_countries.fields.CountryField(default='VE', max_length=2, verbose_name='Nacionalidad'),
        ),
    ]
