# Generated by Django 5.1.6 on 2025-03-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(help_text='Ejemplo: nombre@dominio.com o N/A', max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
