# Generated by Django 5.1.6 on 2025-02-20 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_documentocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='notas',
        ),
        migrations.CreateModel(
            name='NotaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_cliente', to='crm.cliente')),
            ],
            options={
                'verbose_name': 'Nota de Cliente',
                'verbose_name_plural': 'Notas de Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
