# Generated by Django 5.1.6 on 2025-02-20 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_cliente_notas_notacliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocliente',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('contrato', 'Contrato'), ('identificacion', 'Identificación'), ('otros', 'Otros')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='archivo',
            field=models.FileField(upload_to='clientes/documentos/%Y/%m/%d/'),
        ),
    ]
