# Generated by Django 5.1.6 on 2025-02-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_cliente_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula_pasaporte',
            field=models.CharField(help_text='Números para cédula dominicana o número de pasaporte internacional', max_length=20, unique=True, verbose_name='Cédula/Pasaporte'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='movil',
            field=models.CharField(help_text='Formato internacional: +18091234567 o "N/A" si no aplica', max_length=20, verbose_name='Móvil'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Formato internacional: +18091234567 o "N/A" si no aplica', max_length=20, verbose_name='Teléfono'),
        ),
    ]
