# Generated by Django 5.1.6 on 2025-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_cliente_cedula_pasaporte_alter_cliente_movil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='movil',
            field=models.CharField(help_text='Ej: +1 (809) 123-4567 o N/A', max_length=30, verbose_name='Móvil'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Ej: +1 (809) 123-4567 o N/A', max_length=30, verbose_name='Teléfono'),
        ),
    ]
