# Generated by Django 5.1.6 on 2025-02-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_cliente_movil_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='movil',
            field=models.CharField(help_text='Formato internacional: 8091234567 o "N/A" si no aplica', max_length=20, verbose_name='Móvil'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Formato internacional: 8091234567 o "N/A" si no aplica', max_length=20, verbose_name='Teléfono'),
        ),
    ]
