# Generated by Django 5.1.6 on 2025-03-18 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitacionReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Habitaciones reservadas',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reserva', models.CharField(choices=[('hotel', 'Hotel/Resort'), ('tour', 'Tour'), ('transporte', 'Transporte'), ('otros', 'Otros')], default='hotel', max_length=20)),
                ('fecha_entrada', models.DateField(null=True)),
                ('fecha_salida', models.DateField(null=True)),
                ('adultos', models.PositiveIntegerField(default=1)),
                ('adolescentes', models.PositiveIntegerField(default=0)),
                ('ninos', models.PositiveIntegerField(default=0)),
                ('infantes', models.PositiveIntegerField(default=0)),
                ('paso_actual', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.cliente')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
