# Generated by Django 5.1.6 on 2025-03-12 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('is_other', models.BooleanField(default=False, verbose_name="Es 'Otros'")),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('empresa', 'Empresa')], max_length=10)),
                ('manual_hotel', models.CharField(blank=True, max_length=100)),
                ('adultos', models.PositiveIntegerField(default=1)),
                ('ninos', models.PositiveIntegerField(default=0)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('tarifa_adulto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_nino', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas_cliente', models.TextField(blank=True)),
                ('notas_suplidor', models.TextField(blank=True)),
                ('archivos', models.FileField(blank=True, upload_to='reservas/archivos/')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.empresa')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninos_reserva', to='reservas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.PositiveIntegerField(default=2)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_habitacion', to='reservas.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones_reserva', to='reservas.reserva')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.tipohabitacion')),
            ],
        ),
    ]
