# Generated by Django 5.1.6 on 2025-03-15 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='reserva',
            name='adolescentes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='adultos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_entrada',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='infantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ninos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='paso_actual',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.empresa'),
        ),
    ]
