# Generated by Django 5.1.6 on 2025-03-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tipohabitacion',
            name='unique_habitacion_por_hotel',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
