# Generated by Django 5.1.6 on 2025-03-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipohabitacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='temporal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='tipohabitacion',
            constraint=models.UniqueConstraint(condition=models.Q(('temporal', False)), fields=('hotel', 'nombre'), name='unique_nombre_por_hotel'),
        ),
    ]
