# Generated by Django 5.1.6 on 2025-03-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_tipohabitacion_unique_habitacion_por_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='tipohabitacion',
            unique_together={('hotel', 'nombre')},
        ),
    ]
