# Generated by Django 5.1.6 on 2025-03-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_tipohabitacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adolescentes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ninos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='reservas.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Tarifa por noche',
                'verbose_name_plural': 'Tarifas',
            },
        ),
    ]
