# Generated by Django 5.1.6 on 2025-02-13 23:25

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_cliente_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidad',
            field=django_countries.fields.CountryField(default='DO', max_length=2, verbose_name='Nacionalidad'),
        ),
    ]
